### ISSUE TITLE
API SPWorlds возвращает 400 при попытке создать платеж

### ISSUE THREAD

**Issue by ghost** [ronanru/spworlds-lib#1]
**Описание**
При использовании метода **initPayment** API SPWorlds возвращает 400, JSON ответа:
```
{
  statusCode: 400,
  error: 'Bad Request',
  message: 'body must be object'
}
```
**Версии ПО**
Дистрибутив: Debian 11 x86_64
Ядро: 5.10.0-16-amd64 
TSC:  4.7.4
NodeJS: 18.7.0

**Возможное решение проблемы**
По всей видимости можно решить проблему изменением строки **20** в index.js библиотеки:
```diff
-            headers: { Authorization: this.authHeader }
+            headers: { Authorization: this.authHeader,  'Content-Type': 'application/json' }
```

**Код вызова метода**:
```js
const url = await api.initPayment(
        1,
        'https://api.net.laem.fun/api',
        'https://api.net.laem.fun/api/payment/webhook',
        'Оплата товара на nnegative'
);
```

**Comment by matrv** [comment]
Пофиксил, спасибо
